FROM ubuntu:24.04

RUN apt-get update && \
    apt-get install -y --no-install-recommends ca-certificates && \
    rm -rf /var/lib/apt/lists/* && \
    groupadd --system cc && \
    useradd --system --gid cc --home-dir /var/lib/cc-rstationservice --create-home cc

WORKDIR /var/lib/cc-rstationservice

COPY iot-sim-entrypoint.sh /usr/local/bin/iot-sim-entrypoint.sh
COPY CC-rStationService.iot.toml.template /etc/cc-rstationservice/CC-rStationService.toml.template
COPY cc-rstationservice /usr/local/bin/cc-rstationservice

RUN chmod 755 /usr/local/bin/iot-sim-entrypoint.sh /usr/local/bin/cc-rstationservice

USER cc

EXPOSE 50051

ENTRYPOINT ["/usr/local/bin/iot-sim-entrypoint.sh"]
